# Generated by Django 5.1.7 on 2025-06-24 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingresarApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='talla',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
