# Generated by Django 5.1.7 on 2025-07-13 07:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categoriasApp', '0002_categoria'),
        ('ingresarApp', '0003_remove_producto_stock_remove_producto_talla_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categoriasApp.categoria'),
        ),
    ]
