# Generated by Django 5.1.7 on 2025-07-13 07:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categoriasApp', '0002_categoria'),
        ('ingresarApp', '0004_alter_producto_categoria'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Categorias',
        ),
        migrations.AddField(
            model_name='categoria',
            name='padre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategorias', to='categoriasApp.categoria'),
        ),
    ]
