# Generated by Django 5.1.7 on 2025-07-03 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagoApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='empresa_envio',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
