# Generated by Django 5.1.7 on 2025-07-13 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagoApp', '0003_alter_venta_metodo_entrega'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='payment_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='venta',
            name='apellido',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='venta',
            name='empresa_envio',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
