# Generated by Django 5.2.3 on 2025-07-22 04:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingresarApp', '0004_alter_producto_categoria'),
        ('pagoApp', '0004_venta_payment_id_alter_venta_apellido_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='fecha_pago',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='venta',
            name='metodo_pago',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='venta',
            name='origen',
            field=models.CharField(default='web', max_length=20),
        ),
        migrations.AddField(
            model_name='ventaitem',
            name='producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ingresarApp.producto'),
        ),
    ]
